dist: xenial

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  - TARGET=arm-unknown-linux-gnueabi TARGET_CC=arm-frc2019-linux-gnueabi-gcc CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABI=$TARGET_CC

install:
  - rustup target add $TARGET
  - rustup component add clippy

  - wget https://github.com/wpilibsuite/toolchain-builder/releases/download/v2019-3/FRC-2019-Linux-Toolchain-6.3.0.tar.gz -O frc2019.tar.gz
  - tar xf frc2019.tar.gz -C ~
  - export PATH="$PATH:$HOME/frc2019/roborio/bin"

  - wget http://devsite.ctr-electronics.com/maven/release/com/ctre/phoenix/cci/5.14.1/cci-5.14.1-linuxathenastatic.zip -O cci-linuxathena.zip
  - mkdir -p ctre-sys/lib/athena
  - unzip -j cci-linuxathena.zip linux/athena/static/libCTRE_PhoenixCCI.a -d ctre-sys/lib/athena

script:
  - cargo clippy --all-features
  - cargo build --verbose --all-features --all --exclude ctre-bindgen --target $TARGET
